services:
  bot:
    build: .
    environment:
      DATABASE_URL: "postgres://lemonbot:${POSTGRES_PASSWORD}@db/lemonbot"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
      S3_ENDPOINT: "${S3_ENDPOINT}"
      S3_REGION: "${S3_REGION}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "lemonbot"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - lemonbot-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  lemonbot-data:
